// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySteamGamesBack.Data;

#nullable disable

namespace my_steam_games_back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708131659_CreateJobTablesWithProgressStatus")]
    partial class CreateJobTablesWithProgressStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameGenre");
                });

            modelBuilder.Entity("GameTag", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("GameTag");
                });

            modelBuilder.Entity("MySteamGamesBack.Data.GameEntity", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgIconUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InitialPrice")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTimePlayed")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MetacriticScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NegativeReviews")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonnalNotes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonnalScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositiveReviews")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VisibilityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppId");

                    b.HasIndex("StatusId");

                    b.HasIndex("VisibilityId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("MySteamGamesBack.Data.GenreEntity", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AppId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MySteamGamesBack.Data.PopulateJobEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedGames")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalGames")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProgressStatusId");

                    b.ToTable("PopulateJob");
                });

            modelBuilder.Entity("MySteamGamesBack.Data.PopulateJobItemEntity", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgressStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobId", "AppId");

                    b.HasIndex("ProgressStatusId");

                    b.ToTable("PopulateJobItem");
                });

            modelBuilder.Entity("MySteamGamesBack.Data.ProgressStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProgressStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Running"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            Label = "Failed"
                        },
                        new
                        {
                            Id = 5,
                            Label = "Canceled"
                        });
                });

            modelBuilder.Entity("MySteamGamesBack.Data.StatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "100%"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Finished"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Unfinished"
                        },
                        new
                        {
                            Id = 4,
                            Label = "Abandoned"
                        });
                });

            modelBuilder.Entity("MySteamGamesBack.Data.TagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MySteamGamesBack.Data.VisibilityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Visibility");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Visible"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Hidden Manually"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Hidden Default"
                        });
                });

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.HasOne("MySteamGamesBack.Data.GameEntity", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySteamGamesBack.Data.GenreEntity", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameTag", b =>
                {
                    b.HasOne("MySteamGamesBack.Data.GameEntity", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySteamGamesBack.Data.TagEntity", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MySteamGamesBack.Data.GameEntity", b =>
                {
                    b.HasOne("MySteamGamesBack.Data.StatusEntity", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.HasOne("MySteamGamesBack.Data.VisibilityEntity", "Visibility")
                        .WithMany()
                        .HasForeignKey("VisibilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Visibility");
                });

            modelBuilder.Entity("MySteamGamesBack.Data.PopulateJobEntity", b =>
                {
                    b.HasOne("MySteamGamesBack.Data.ProgressStatusEntity", "ProgressStatus")
                        .WithMany()
                        .HasForeignKey("ProgressStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgressStatus");
                });

            modelBuilder.Entity("MySteamGamesBack.Data.PopulateJobItemEntity", b =>
                {
                    b.HasOne("MySteamGamesBack.Data.PopulateJobEntity", "Job")
                        .WithMany("JobItems")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySteamGamesBack.Data.ProgressStatusEntity", "ProgressStatus")
                        .WithMany()
                        .HasForeignKey("ProgressStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("ProgressStatus");
                });

            modelBuilder.Entity("MySteamGamesBack.Data.PopulateJobEntity", b =>
                {
                    b.Navigation("JobItems");
                });
#pragma warning restore 612, 618
        }
    }
}
