// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySteamGamesBack.Data;

#nullable disable

namespace my_steam_games_back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("MySteamGamesBack.Data.Entities.GameEntity", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgIconUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InitialPrice")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastTimePlayed")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetacriticScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NegativeReviews")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonnalNotes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonnalScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositiveReviews")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AppId");

                    b.HasIndex("StatusId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("MySteamGamesBack.Data.Entities.GameGenreEntity", b =>
                {
                    b.Property<int>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameGenres");
                });

            modelBuilder.Entity("MySteamGamesBack.Data.Entities.GenreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MySteamGamesBack.Data.Entities.StatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "100%"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Finished"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Unfinished"
                        },
                        new
                        {
                            Id = 4,
                            Label = "Abandoned"
                        });
                });

            modelBuilder.Entity("MySteamGamesBack.Data.Entities.GameEntity", b =>
                {
                    b.HasOne("MySteamGamesBack.Data.Entities.StatusEntity", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MySteamGamesBack.Data.Entities.GameGenreEntity", b =>
                {
                    b.HasOne("MySteamGamesBack.Data.Entities.GameEntity", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MySteamGamesBack.Data.Entities.GenreEntity", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MySteamGamesBack.Data.Entities.GameEntity", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("MySteamGamesBack.Data.Entities.GenreEntity", b =>
                {
                    b.Navigation("GameGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
